import type { Metadata } from "next";
import { Anek_Devanagari } from "next/font/google";
import "./globals.css";

const inter = Anek_Devanagari({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rakibul Hasan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-color-main`}>{children}</body>
    </html>
  );
}
